### PR TITLE
try using json instead of txt format extension to put and get data

### PR DESCRIPTION
**Pull request by LebzoDev**
- [ ] A simple way to get and put content in a json file
##### file_put_contents('results.json', $jsonData);

- [x] Try associate html css and php in order to avoid puting the same data in your database;
- [x] Define an index file in where is defining all the process of your logique and the others files would have your classes and their logique

### CODE REVIEW

**Comment by Alkaly02** [comment]
### Best feedbacks I ever had.
#### Very useful ones.

Why do you think storing data in json files is better than putting them in .txt files?

In my point of view, I think it's more easy to encode and decode because with .txt file, I have to encode and decode every single 

line of the file.. But with json(as you write it), it's like we just have to serialize once ! **### POWERFUL !!!!!!!!**

**Comment by LebzoDev** [comment]
You would notice like what you put in your txt files is already in JSON format. So using JSON file would make u avoid using a bunch of php methods in order to treat or read file's content like fopen, fwrite ... With JSON file you could use too JSON_PRETTY_PRINT as the second parameter while encoding data ex: json_encode($data, JSON_PRETTY_PRINT) and this will make your file more readable and clear.

**Comment by Alkaly02** [comment]
## WEEEEEEEEL EXPLAINED

I'll take care of your feedbacks **master**.

Thanks a lot. I appreciate !

**Comment by LebzoDev** [comment]
> ## WEEEEEEEEL EXPLAINED
> I'll take care of your feedbacks **master**.
> 
> Thanks a lot. I appreciate !
You're welcome master it's a pleasure

**Pull request merged**
